<!--  ////////////////// -->
<!DOCTYPE html>
<!--[if lt IE 7 ]><html class="ie ie6" lang="fr"> <![endif]-->
<!--[if IE 7 ]><html class="ie ie7" lang="fr"> <![endif]-->
<!--[if IE 8 ]><html class="ie ie8" lang="fr"> <![endif]-->
<!--[if (gte IE 9)|!(IE)]><!--><html lang="fr"> <!--<![endif]-->
<head>

	<!-- Basic Page Needs
  ================================================== -->
	<meta charset="utf-8">
	<title>Bookfaker</title>
	<meta name="description" content="">

	<!-- Mobile Specific Metas
  ================================================== -->
	<!-- <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1"> -->

	<!-- CSS
  ================================================== -->
        
	<link rel="stylesheet" href="<?php echo $this->baseUrl("css/main.css"); ?>">
	<link rel="stylesheet" href="<?php echo $this->baseUrl("css/home.css"); ?>">
	<link rel="stylesheet" href="<?php echo $this->baseUrl("css/blog.css"); ?>">
	<link rel="stylesheet" href="<?php echo $this->baseUrl("css/contact.css"); ?>">
	<link rel="stylesheet" href="<?php echo $this->baseUrl("css/about.css"); ?>">
	<link rel="stylesheet" href="<?php echo $this->baseUrl("css/post.css"); ?>">
	<link rel="stylesheet" href="<?php echo $this->baseUrl("css/league_tables.css"); ?>">
	<link rel="stylesheet" href="<?php echo $this->baseUrl("css/basic-styles.css"); ?>">
	<link rel="stylesheet" href="<?php echo $this->baseUrl("css/gallery_1.css"); ?>">
	<link rel="stylesheet" href="<?php echo $this->baseUrl("css/prettyPhoto.css"); ?>">
	<link rel="stylesheet" href="<?php echo $this->baseUrl("css/prettyPhoto.css"); ?>">

	<!--[if lt IE 9]>
		<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
		<link rel="stylesheet" href="<?php echo $this->baseUrl("css/ie_fix.css"); ?>">
	<![endif]-->


	<script type="text/javascript">
		var gOverride = {
		  urlBase: 'http://gridder.andreehansson.se/releases/latest/',
		  gColor: '#ff0000',
		  gColumns: 16,
		  gOpacity: 0.35,
		  gWidth: 10,
		  pColor: '#C0C0C0',
		  pHeight: 15,
		  pOffset: 0,
		  pOpacity: 0.55,
		  center: true,
		  invert: true,
		  gEnabled: true,
		  pEnabled: false,
		  setupEnabled: true,
		  fixFlash: false,
		  size: 960
		};
	</script>

	<script>
		(function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
		(i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
		m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
		})(window,document,'script','//www.google-analytics.com/analytics.js','ga');

		ga('create', 'UA-42715016-1', 'bookfaker.com');
		ga('send', 'pageview');
	</script>

	<!-- Favicons
	================================================== -->
	<link rel="shortcut icon" href="<?php echo $this->baseUrl("images/favicon.ico"); ?>">
	<link rel="apple-touch-icon" href="<?php echo $this->baseUrl("images/apple-touch-icon.png"); ?>">
	<link rel="apple-touch-icon" sizes="72x72" href="<?php echo $this->baseUrl("images/apple-touch-icon-72x72.png"); ?>">
	<link rel="apple-touch-icon" sizes="114x114" href="<?php echo $this->baseUrl("images/apple-touch-icon-114x114.png"); ?>">

</head>
<body ng-app="bookfaker">

<!-- To Top button -->
<a href="#top" id="toTop">&#8593;</a>


	<!-- Page Layout
	================================================== -->

	<!-- Header Styles -->
	<header id="mainHeader" class="expand">
		<div class="container">
			<div id="logo" class="five columns">
				<h1><a href="index.html">BookFaker <em>Un nouveau site de paris fictifs en ligne</em></a></h1>
			</div>
			<div id="loginBox" class="loginBox eleven columns">
				<form method="post" action="<?php echo $this->url(array('module' => 'frontend','controller'=>'user','action'=>'login'), null, true); ?>">
                                    <?php if(Bookfaker_Control::isLogged()): ?>
                                        <span style="font:normal 13px/13px 'Open Sans',Arial,sans-serif"><img src="<?php echo $this->baseUrl("images/user.png"); ?>"> <?php echo Bookfaker_Control::userInfos()->getUsername()?>  - <strong></strong><?php echo Bookfaker_Control::userInfos()->getMoneybank()?> B</br></span>
                                        <span style="font:normal 13px/13px 'Open Sans',Arial,sans-serif"><a class="link" href="<?php echo $this->url(
                                            array(
                                                'module' => 'frontend',
                                                'controller'=>'user',
                                                'action'=>'logout'
                                                ), null, true); ?>">Logout</a></span>
                                    <?php else: ?>
                                        <input type="text" name="username" id="headerLogin" placeholder="Pseudo...">
                                        <input type="password" name="password" id="headerPassword" placeholder="Mot de passe...">
                                        <a href="<?php echo $this->url(array('module' => 'frontend','controller'=>'user','action'=>'register'), null, true); ?>" id="submitJoin" class="noTransition">Inscrivez-vous</a>
                                        <input type="submit" name="submitLogin" id="submitLogin" class="noTransition" value="Connexion">
                                    <?php endif; ?>
				</form>
			</div>
		</div>
	</header>
	<hr><!-- end header section -->
	<nav id="mainNav" class="container">
		<ul>
			<li><a class="current" href="<?php echo $this->url(array('module' => 'frontend','controller'=>'index','action'=>'index'),null, true); ?>">Accueil</a></li>
			<?php foreach($this->sports  as $sport): ?>
                            <li><a href="<?php echo $this->url(array('module' => 'frontend','controller'=>'index','action'=>'paris', "sport" => $sport->name),null, true); ?>"><?php echo $sport->name;?></a>
                                    <ul>
                                        <?php foreach($sport->championships as $idChampionship => $championship): ?>
                                            <a href="<?php echo $this->url(array('module' => 'frontend','controller'=>'index','action'=>'paris', "sport" => $sport->name, "championship" => $idChampionship),null, true); ?>"><?php echo $championship;?></a>
                                        <?php endforeach;?>
                                    </ul>
                            </li>
                        <?php endforeach;?>

			<li><a href="<?php echo $this->url(array('module' => 'frontend','controller'=>'gift','action'=>'index'),null, true); ?>">Boutique</a></li>
			<li><a href="<?php echo $this->url(array('module' => 'frontend','controller'=>'user','action'=>'profile'),null, true); ?>">Mon compte</a></li>
		</ul>
	</nav><!-- end main nav section -->

	<!-- 
	<div id="pageHeader" class="container">
		<div class="stripe"></div>
		<div id="info">
			<span class="topLeft"></span>
			<span class="topRight"></span>
			<span class="bottomRight"></span>
			<span class="bottomLeft"></span>
			<h1>Titre</h1>
			<em>Phrase.</em>
			<div id="breadCrumbs">
				<p><a href="index.html">Accueil</a> / <a href="inscription.html" class="active">Page Active</a></p>
			</div>
		</div>
	</div><!-- end of page header -->

	<div id="contetnContainer" class="container">
		<div class="leftColumn eleven columns">
                    <?php echo $this->layout()->content ?>
			<br />
			<object style="margin:10px 86px 0;" type="application/x-shockwave-flash" data="http://www.gambling-affiliation.com/tracking/visuels/28093.swf" width="468" height="60"><param name="movie" value="http://www.gambling-affiliation.com/tracking/visuels/28093.swf"><param name="quality" value="high"><param name="flashvars" value=""></object>
		</div><!-- left columns -->

		<div class="rightColumn five columns">
			<section id="blogPosts">
				<header>
					<h2>Votre coupon</h2>
				</header>
				<div ng-controller="menuCtrl">
					<!--<input ng-change="saveSessionCoupon()" ng-model="coupon.type" type="radio" name="type" value="0" checked> Simple<br>
					<input ng-change="saveSessionCoupon()" ng-model="coupon.type" type="radio" name="type" value="1" > Combiné-->
                                        <h3 class="tabActive" style="width:49%;float:left;"><a href="" ng-click="saveSessionCoupon(0)" >SIMPLE</a></h3>
					<h3 class="tabInactive" style="width:49%;float:right;"><a href="" ng-click="saveSessionCoupon(1)">COMBINE</a></h3>
					<div class="post clearfix">
						<div ng-repeat="bet in coupon.bets" class="metaData clearfix" style="width:280px;margin:0;">
							<p><a href="#">{{bet.match.nameTeamOne}} vs {{bet.match.nameTeamTwo}}</a></p>
							<p style="float:right;"><a href="" ng-click="removeBet($index)">X</a></p>
							</br>
							<p>Pronostic : </p>
							<p style="float:right;">{{getOdds(bet)}}</p>								
						</div>
					</div>
					<div class="post clearfix">
						<div class="metaData clearfix" style="width:280px;margin:0;">
							<p ng-show="1==coupon.type" class="">Cote totale :</p>
							<p ng-show="1==coupon.type" class="" style="float:right;">{{calculCote()}}</p>
							</br>
							<p class="">Mise :</p>
							<p class="" style="float:right;"><input ng-change="saveSessionCoupon()" ng-model="coupon.stacke" type="text" name="mise" id="mise" style="width: 60px;height: 20px;padding: 0px 10px;margin: 0;"></p>
							</br>
							<p class="" style="margin: 5px 0">Gains Possible :</p>
							<p class="" style="float:right;margin: 5px -60px">{{calculGains()}} B</p>
							</br>
                                                        <p ng-show="isSaved" >Pari(s) sauvegardé(s) !</p>
							<p class="" style="float:right;margin-top:10px"><button ng-click="saveBets()" class="button">Valider</button></p>
						</div>
					</div>
					<div ng-show="!isLogged">Vous devez être connectés pour parier.
						<a href="<?php echo $this->url(array('module' => 'frontend', 'controller'=>'user', 'action'=>'register')); ?>">Inscrivez-vous ici</a> si vous n'avez pas de compte.
					</div>
				</div>
			</section>
			</br>
			<object type="application/x-shockwave-flash" data="http://www.gambling-affiliation.com/tracking/visuels/28096.swf" width="280" height="280"><param name="movie" value="http://www.gambling-affiliation.com/tracking/visuels/28096.swf"><param name="quality" value="high"><param name="flashvars" value=""></object>
			</br>
			<section id="blogPosts">
				<header>
					<h2>Top Parieurs</h2>
				</header>
				<div>
                                    <h3 class="tabActive" style="width:32%;float:left;"><a ng-click="loadBestUsers(week)" href="">Semaine</a></h3>
                                    <h3 class="tabInactive" style="width:32%;float:left;margin:0 2%"><a ng-click="loadBestUsers(month)"href="">Mois</a></h3>
                                    <h3 class="tabInactive" style="width:32%;float:right;"><a ng-click="loadBestUsers()" href="">All Time</a></h3>
                                    <div ng-repeat="user in bestUsers" class="post clearfix">
                                            <div class="metaData clearfix" style="width:280px;margin:0;">
                                                    <p class=""><a href="#">Camille B.</a></p>
                                                    <p class="" style="float:right;">7200 B</p>
                                            </div>
                                    </div>
				</div>
			</section>
		</div><!-- right column -->
	</div><!-- end of content container -->

	<section id="footer" class="expand">
		<div class="footerUpper container">
			<section class="footerAbout five columns">
				<h1><a href="index.html">BookFaker <em>Un nouveau site de paris en ligne fictif</em></a></h1>
				<p>Site de paris fictifs regroupant le sport, les actualités people, politiques. Testez gratuitement vos talents de parieurs et gagnez de nombreux cadeaux. Le projet démarre le site est donc en cours de construction. </p>
				<a href="#" class="login">Login</a>
				<a href="#" class="join">Join</a>
			</section><!-- footer about -->
			<section class="footerNav five columns">
				<header class="reverse">
					<h2>Menu</h2>
				</header>
				<ul>
					<li><a href="index.html">Accueil</a></li>
					<li><a href="profile.html">Mon compte</a></li>
					<li><a href="shop.html">Boutique</a></li>
					<li class="last"><a href="contact.html">Contact</a></li>
				</ul>
			</section><!-- footer nav -->
			<section class="footerNav six columns">
				<header class="reverse">
					<h2>Sports</h2>
				</header>
				<ul>
					<li><a href="football.html">Football</a></li>
					<li><a href="tennis.html">Tennis</a></li>
					<li><a href="basket.html">Basket</a></li>
				</ul>
			</section><!-- footer nav -->
		</div><!-- end of footerUpper div -->
		<div class="footerBottom expand">
			<div class="container">
				<div class="footerSocial eight columns">
					<ul>
						<li><a href="#" class="facebook">Facebook</a></li>
					</ul>
				</div><!-- footer social -->
				<div class="copyRights eight columns">
					<p>copyright&copy; 2013, bookfaker.com</p>
				</div><!-- copyrights -->
			</div>
		</div><!-- footer bottom -->
	</section><!-- end of footer section -->



	<!-- JS
	================================================== -->
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.8.2/jquery.min.js"></script>
	<script src="<?php echo $this->baseUrl("js/jquery.waitforimages.js"); ?>"></script>
	<script src="<?php echo $this->baseUrl("js/jquery.cycle2.min.js"); ?>"></script>
	<script src="<?php echo $this->baseUrl("js/jquery.cycle2.tile.min.js"); ?>"></script>
	<script src="<?php echo $this->baseUrl("js/jcarousellite_1.0.1.min.js"); ?>"></script>
	<script src="<?php echo $this->baseUrl("js/jquery.tweet.js"); ?>"></script>
	<script src="<?php echo $this->baseUrl("js/main_func.js"); ?>"></script>
	<script src="<?php echo $this->baseUrl("js/home_func.js"); ?>"></script>
	<script src="<?php echo $this->baseUrl("js/post_func.js"); ?>"></script>
	<script src="<?php echo $this->baseUrl("js/league_tables_func.js"); ?>"></script>
	<script src="<?php echo $this->baseUrl("js/angular.min.js"); ?>"></script>
	<script src="<?php echo $this->baseUrl("js/script.js"); ?>"></script>
	<script src="<?php echo $this->baseUrl("js/controllers/index.js"); ?>"></script>

<!-- End Document
================================================== -->
</body>
</html>