

<!--			<section id="galleryNav" class="eleven columns clearfix">
				<header>
					<h2>Boutique</h2>
				</header>

				<div id="categContainer" class="clearfix">
					<div class="eleven columns alpha filter">
						<h3>Filtres<span></span></h3>
						<ul id="categoriesLinks">
							<li class="selected"><a href="#" class="all">Tout</a> / </li>
							<li><a href="#" class="maillots">Maillots officiels</a> / </li>
							<li><a href="#" class="hightech">High-tech</a> / </li>
							<li><a href="#" class="goodies">Goodies</a> / </li>
							<li><a href="#" class="equipements">Equipements sportifs</a> / </li>
							<li><a href="#" class="jeuxvideos">Jeux vid&eacute;os</a> / </li>
							<li><a href="#" class="billeterie">Billeterie</a></li>
						</ul>
					</div> filter div 
				</div>
			</section> gallery nav section -->
                        <p><?php echo $this->message ? $this->message : ''; ?></p>

			<section id="gallery_1" class="eleven columns clearfix">
				<ul class="designs">
                                    
                                        <?php foreach($this->gifts as $gift): ?>
                                            <li class="item clearfix" data-id="id-1" data-type="maillots">
                                                        <img src="<?php echo $this->baseUrl(); ?>/images/<?php echo $gift->getImage();?>" />
                                                        <div class="titleAndMeta clearfix">
                                                            <h3><a href="?idGift=<?php echo $gift->getId(); ?>"><?php echo $gift->getName() ; ?></a> -<?php echo  $gift->getBookies(); ?> Bookies</h3>
                                                        </div>
                                                </li>
                                            
                                        <?php endforeach; ?>
<!--					<li class="item clearfix" data-id="id-1" data-type="maillots">
						<div class="image-hover clearfix">
							<a href="<?php echo $this->baseUrl("images/maillots/psg_2014.jpg");?>" rel="prettyPhoto[gallery1]" class="zoom">Zoom</a>
						</div>
						<img src="<?php $this->baseUrl("images/maillots/psg_2014.jpg"); ?>" alt="">
						<div class="titleAndMeta clearfix">
							<h3><a href="#">Maillot PSG 2014</a></h3>
						</div>
						<p>Magnifique maillot de football de l'&eacute;quipe du PSG pour la saison 2013/14.</p>
					</li>-->

<!--					<li class="item" data-id="id-2" data-type="goodies">
						<div class="image-hover clearfix">
							<a href="<?php echo $this->baseUrl("images/fax.jpg"); ?>" rel="prettyPhoto[gallery1]" class="zoom">Zoom</a>
						</div>
						<img src="<?php echo $this->baseUrl("images/fax.jpg"); ?>" alt="">
						<div class="titleAndMeta clearfix">
							<h3><a href="#">Stylo ballon</a></h3>
						</div>
						<p>Un petit stylo pour remplir vos grille de paris.</p>
					</li>

					<li class="item noRight" data-id="id-3" data-type="jeuxvideos">
						<div class="image-hover clearfix">
							<a href="<?php echo $this->baseUrl("images/fax.jpg"); ?>" rel="prettyPhoto[gallery1]" class="zoom">Zoom</a>
						</div>
						<img src="<?php echo $this->baseUrl("images/fax.jpg"); ?>" alt="">
						<div class="titleAndMeta clearfix">
							<h3><a href="#">Fifa 14</a></h3>
						</div>
						<p>Jeu de foot sur console.</p>
					</li>-->
				</ul>
			</section><!-- gallery 4 columns -->

