<?php

namespace Application\Model\Entities;

use Doctrine\ORM\EntityRepository;

/**
 * OddsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OddsRepository extends EntityRepository
{
}
