<section id="blogPosts" ng-controller="indexCtrl" ng-init="init(<?php echo $this->idSport . ',' . $this->idChampionship; ?>)">
    <header>
            <h2>Tous les championnats</h2>
    </header>
    <div style="text-align: center" ng-show="!isDataLoaded">
        <img src="<?php echo $this->baseURL("/images/preloader.gif");?>"/>
    </div>
    <div ng-repeat="o in odds" class="post clearfix">
            <div class="date" style="width:120px">
                    <p style="padding:0; line-height:27px">{{o.date}}</p>
            </div>
            <h3><a href="#" style="margin: 8px 0 0 10px;width:200px">{{o.championship}}</a></h3>
            <div class="metaData clearfix" style="width:300px">
                    <p class=""><a href="#">{{o.nameTeamOne|truncate:15}} - {{o.nameTeamTwo|truncate:15}}</a></p>
                    <p class="" style="float:right; margin:0 15px"><a href="#">{{o.oddsTeamOne}}</a></p>
                    <p class="" style="float:right; margin:0 15px"><a href="#">{{o.oddsDraw}}</a></p>
                    <p class="" style="float:right; margin:0 15px"><a href="#">{{o.oddsTeamTwo}}</a></p>
            </div>
    </div>
</section>