		<section id="homeSlider">
			<span class="topLeft"></span>
			<span class="topRight"></span>
			<span class="bottomRight"></span>
			<span class="bottomLeft"></span>

			<div class="cycle-slideshow" 
		        data-cycle-fx="tileBlind"
		        data-cycle-timeout=0
		        data-cycle-slides="> div"
		        data-cycle-prev="div.prev"
		        data-cycle-next="div.next"
		        data-cycle-pager="#slidePager"
		        >
		        <div>
		        	<img src="<?php echo $this->baseUrl("images/preview_images/home_slider_1.jpg");?>" alt="">
		        	<div class="cycle-overlay">
						<p>John Abraham en visite chez les Cardinals.</p>
					</div>
				</div>
				<div>
		        	<img src="<?php echo $this->baseUrl("images/preview_images/home_slider_2.jpg");?>" alt="">
		        	<div class="cycle-overlay">
						<p>Areola : «Je suis prêt».</p>
					</div>
				</div>
				<div>
		        	<img src="<?php echo $this->baseUrl("images/preview_images/home_slider_3.jpg");?>" alt="">
		        	<div class="cycle-overlay">
						<p>N. Robinson rejoint Denver.</p>
					</div>
				</div>
				<div>
		        	<img src="<?php echo $this->baseUrl("images/preview_images/home_slider_4.jpg");?>" alt="">
		        	<div class="cycle-overlay">
						<p>Chamonix sacre Desgranges.</p>
					</div>
				</div>
			</div>

			<div class="prev"></div>
    		<div class="next"></div>
		</section><!-- home slider -->
                <section id="blogPosts" ng-controller="indexCtrl" ng-init="init(<?php echo $this->idSport . ',' . $this->idChampionship; ?>)">
                    <div style="text-align: center" ng-show="!isDataLoaded">
                        <img src="<?php echo $this->baseURL("/images/preloader.gif");?>"/>
                    </div>
                    <div ng-repeat="obc in oddsByChampionship">
                        <header>
                            <h2><a href="<?php echo $this->url(array('module' => 'frontend','controller'=>'index','action'=>'sport'), null, true); ?>" style="color: #55ccd9;">{{obc.name}}</a></h2>
                        </header>
                        <div  ng-repeat="o in obc.odds" class="post clearfix">
                            <div class="date" style="width:140px">
                                    <p style="padding:0; line-height:27px">{{o.date}}</p>
                            </div>
                            <h3>{{obc.name}}</h3>
                            <div class="metaData clearfix" style="width:490px">
                                <p>{{o.nameTeamOne|truncate:20}} vs {{o.nameTeamTwo|truncate:20}}</p>
                                <p ng-click="addBet(o, 1)" style="float:right; margin:0 15px;width:20px;"><a href="">{{o.oddsTeamOne}}</a></p>
                                <p ng-click="addBet(o, 0)" style="float:right; margin:0 15px;width:20px;"><a href="">{{o.oddsDraw}}</a></p>
                                <p ng-click="addBet(o, 2)" style="float:right; margin:0 15px;width:20px;"><a href="">{{o.oddsTeamTwo}}</a></p>
                            </div>
                        </div>
                    </div>
                </section>

		<!--<section id="blogPosts">
			<header>
				<h2>Meilleurs Paris Football</h2>
			</header>
			<div class="post clearfix">
				<div class="date" style="width:120px">
					<p style="padding:0; line-height:27px">25/01/2013 20h00</p>
				</div>
				<h3><a href="#" style="margin: 8px 0 0 10px;width:200px">Euro 2014</a></h3>
				<div class="metaData clearfix" style="width:300px">
					<p class=""><a href="#">Angleterre - France</a></p>
					<p class="" style="float:right; margin:0 15px"><a href="#">3.55</a></p>
					<p class="" style="float:right; margin:0 15px"><a href="#">2.60</a></p>
					<p class="" style="float:right; margin:0 15px"><a href="#">1.55</a></p>
				</div>
			</div>
			<div class="post clearfix">
				<div class="date" style="width:120px">
					<p style="padding:0; line-height:27px">25/01/2013 20h00</p>
				</div>
				<h3><a href="#" style="margin: 8px 0 0 10px;width:200px">Euro 2014</a></h3>
				<div class="metaData clearfix" style="width:300px">
					<p class=""><a href="#">Angleterre - France</a></p>
					<p class="" style="float:right; margin:0 15px"><a href="#">3.55</a></p>
					<p class="" style="float:right; margin:0 15px"><a href="#">2.60</a></p>
					<p class="" style="float:right; margin:0 15px"><a href="#">1.55</a></p>
				</div>
			</div>
			<div class="post clearfix">
				<div class="date" style="width:120px">
					<p style="padding:0; line-height:27px">25/01/2013 20h00</p>
				</div>
				<h3><a href="#" style="margin: 8px 0 0 10px;width:200px">Euro 2014</a></h3>
				<div class="metaData clearfix" style="width:300px">
					<p class=""><a href="#">Angleterre - France</a></p>
					<p class="" style="float:right; margin:0 15px"><a href="#">3.55</a></p>
					<p class="" style="float:right; margin:0 15px"><a href="#">2.60</a></p>
					<p class="" style="float:right; margin:0 15px"><a href="#">1.55</a></p>
				</div>
			</div>
			<div class="post clearfix">
				<div class="date" style="width:120px">
					<p style="padding:0; line-height:27px">25/01/2013 20h00</p>
				</div>
				<h3><a href="#" style="margin: 8px 0 0 10px;width:200px">Euro 2014</a></h3>
				<div class="metaData clearfix" style="width:300px">
					<p class=""><a href="#">Angleterre - France</a></p>
					<p class="" style="float:right; margin:0 15px"><a href="#">3.55</a></p>
					<p class="" style="float:right; margin:0 15px"><a href="#">2.60</a></p>
					<p class="" style="float:right; margin:0 15px"><a href="#">1.55</a></p>
				</div>
			</div>
			<div class="post clearfix">
				<div class="date" style="width:120px">
					<p style="padding:0; line-height:27px">25/01/2013 20h00</p>
				</div>
				<h3><a href="#" style="margin: 8px 0 0 10px;width:200px">Euro 2014</a></h3>
				<div class="metaData clearfix" style="width:300px">
					<p class=""><a href="#">Angleterre - France</a></p>
					<p class="" style="float:right; margin:0 15px"><a href="#">3.55</a></p>
					<p class="" style="float:right; margin:0 15px"><a href="#">2.60</a></p>
					<p class="" style="float:right; margin:0 15px"><a href="#">1.55</a></p>
				</div>
			</div>
		</section> -->	

<section id="blogPosts" ng-controller="indexCtrl" ng-init="init(<?php echo 'Football ,1'; ?>)">
    <header>
            <h2>Tous les championnats</h2>
    </header>
    <div style="text-align: center" ng-show="!isDataLoaded">
        <img src="<?php  echo $this->baseURL("/images/preloader.gif");?>"/>
    </div>
    <div ng-repeat="o in odds" class="post clearfix">
		<div class="date" style="width:120px">
			<p style="padding:0; line-height:27px">{{o.date|truncate:13}}</p>
		</div>
		<h3><a href="#" style="margin: 8px 0 0 10px;width:180px">{{o.championship}}</a></h3>
		<div class="metaData clearfix" style="width:320px">
			<p class=""><a href="#">{{o.nameTeamOne|truncate:10}} - {{o.nameTeamTwo|truncate:10}}</a></p>
			<p ng-click="addBet(o, 1)" class="" style="float:right;  margin:0 15px;width:20px;"><a href="#">{{o.oddsTeamOne}}</a></p>
			<p ng-click="addBet(o, 0)" class="" style="float:right;  margin:0 15px;width:20px;"><a href="#">{{o.oddsDraw}}</a></p>
			<p ng-click="addBet(o, 2)" class="" style="float:right;  margin:0 15px;width:20px;"><a href="#">{{o.oddsTeamTwo}}</a></p>
		</div>
	</div>
</section>

