<section id="blogPosts" ng-controller="sportCtrl" ng-init="init(<?php echo $this->idSport . ',' . $this->idChampionship; ?>)">
    <div style="text-align: center" ng-show="!isDataLoaded">
        <img src="<?php echo $this->baseURL("/images/preloader.gif");?>"/>
    </div>
    <div ng-repeat="obc in oddsByChampionship">
        <header>
            <h2><a href="<?php echo $this->url(array('module' => 'frontend','controller'=>'index','action'=>'sport'), null, true); ?>" style="color: #55ccd9;">{{obc.name}}</a></h2>
        </header>
        <div  ng-repeat="o in obc.odds" class="post clearfix">
            <div class="date" style="width:140px">
                    <p style="padding:0; line-height:27px">{{o.date}}</p>
            </div>
            <div class="metaData clearfix" style="width:490px">
                <p>{{o.nameTeamOne|truncate:20}} vs {{o.nameTeamTwo|truncate:20}}</p>
                <p ng-click="addBet(o, 1)" style="float:right; margin:0 15px;width:20px;"><a href="">{{o.oddsTeamOne}}</a></p>
                <p ng-click="addBet(o, 0)" style="float:right; margin:0 15px;width:20px;"><a href="">{{o.oddsDraw}}</a></p>
                <p ng-click="addBet(o, 2)" style="float:right; margin:0 15px;width:20px;"><a href="">{{o.oddsTeamTwo}}</a></p>
            </div>
        </div>
    </div>
</section>
